config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "summary#index"

  resources :disbursements, only: [:index]
  resources :monthly_fees, only: [:index]
  resources :orders, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/date_scopable.rb
module DateScopable
  extend ActiveSupport::Concern

  included do
    scope :as_of_date_desc, -> { order(as_of_date: :desc) }
    scope :for_year, ->(year) { where("EXTRACT(YEAR FROM as_of_date) = ?", year) }
  end
end

app/models/disbursement.rb
class Disbursement < ApplicationRecord
  include DateScopable

  belongs_to :merchant

  has_many :orders

  monetize :amount_in_cents, as: "amount"
  monetize :commission_fee_in_cents, as: "commission_fee"

  scope :yearly_summary, -> {
    disbursements_subquery = <<~SQL
      SELECT
        CAST(EXTRACT(YEAR FROM as_of_date) AS int) AS year,
        COUNT(*) AS disbursements_count,
        SUM(amount_in_cents) AS amount_in_cents,
        SUM(commission_fee_in_cents) AS commission_fee_in_cents
      FROM disbursements
      GROUP BY year
    SQL

    monthly_fees_subquery = <<~SQL
      SELECT
        CAST(EXTRACT(YEAR FROM as_of_date) AS int) AS year,
        COUNT(*) AS monthly_fees_count,
        SUM(fee_in_cents) AS monthly_fee_in_cents
      FROM monthly_fees
      GROUP BY year
    SQL

    from("(#{disbursements_subquery}) disbursements")
      .joins("LEFT JOIN (#{monthly_fees_subquery}) monthly_fees ON disbursements.year = monthly_fees.year")
      .select(
        "disbursements.year",
        "disbursements.disbursements_count",
        "disbursements.amount_in_cents",
        "disbursements.commission_fee_in_cents",
        "COALESCE(monthly_fees.monthly_fees_count, 0) AS monthly_fees_count",
        "COALESCE(monthly_fees.monthly_fee_in_cents, 0) AS monthly_fee_in_cents"
      )
      .order("disbursements.year ASC")
  }
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  enum :disbursement_frequency, %w[daily weekly].index_by(&:itself), validate: true

  has_many :disbursements
  has_many :monthly_fees

  scope :on_weekday, ->(date:) {
    weekly.where("EXTRACT(DOW FROM live_on) = ?", date.wday)
  }

  scope :with_minimum_monthly_fee, -> {
    where("minimum_monthly_fee_in_cents > 0")
  }

  class << self
    def valid_disbursement_frequency?(frequency)
      frequency.in?(disbursement_frequencies.keys)
    end
  end
end

app/models/monthly_fee.rb
class MonthlyFee < ApplicationRecord
  include DateScopable

  belongs_to :merchant

  monetize :fee_in_cents, as: "fee"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :merchant
  belongs_to :disbursement, optional: true

  monetize :amount_in_cents, as: "amount"
  monetize :commission_fee_in_cents, as: "commission_fee"

  scope :grouped_for_disbursement, ->(date:) {
    eligible_for_disbursement(date: date)
      .group(:merchant_id)
      .select(
        "merchant_id",
        "SUM(amount_in_cents) - SUM(commission_fee_in_cents) as amount_in_cents",
        "SUM(commission_fee_in_cents) as commission_fee_in_cents",
        "ARRAY_AGG(orders.id) as order_ids"
      )
  }

  scope :eligible_for_disbursement, ->(date:) {
    not_disbursed.eligible_for_disbursement_daily(date: date)
      .or(
        not_disbursed.eligible_for_disbursement_weekly(date: date)
      )
  }
  scope :eligible_for_disbursement_daily, ->(date:) {
    placed_on(date: date)
      .joins(:merchant)
      .merge(Merchant.daily)
  }
  scope :eligible_for_disbursement_weekly, ->(date:) {
    joins(:merchant)
      .merge(Merchant.on_weekday(date: date))
  }
  scope :placed_on, ->(date:) { where(placed_at: date) }
  scope :not_disbursed, -> { where(disbursement_id: nil) }

  scope :grouped_for_monthly_fee, ->(date_range) {
    where(placed_at: date_range)
      .joins(:merchant)
      .merge(Merchant.with_minimum_monthly_fee)
      .group("merchant_id, merchants.minimum_monthly_fee_in_cents")
      .select(
        "merchant_id",
        "merchants.minimum_monthly_fee_in_cents - SUM(commission_fee_in_cents) as monthly_fee_in_cents"
      )
      .having("SUM(commission_fee_in_cents) < merchants.minimum_monthly_fee_in_cents")
  }

  scope :months_with_orders, -> {
    select("DATE_TRUNC('month', placed_at) AS placed_month")
      .group("DATE_TRUNC('month', placed_at)")
  }

  scope :grouped_by_placed_at, -> {
    group(:placed_at).select("placed_at")
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/disbursements_controller.rb
class DisbursementsController < ApplicationController
  def index
    @year = params.fetch(:year)
    @disbursements = Disbursement.for_year(@year).as_of_date_desc.includes(:merchant)
  end
end

app/controllers/monthly_fees_controller.rb
class MonthlyFeesController < ApplicationController
  def index
    @year = params.fetch(:year)
    @monthly_fees = MonthlyFee.for_year(@year).as_of_date_desc.includes(:merchant)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @disbursement = Disbursement.find_by_reference(params.fetch(:disbursement_reference))
    @orders = @disbursement.orders.includes(:merchant).order(placed_at: :desc)
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def index
    @summary = Disbursement.yearly_summary
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/disbursements/index.haml
.breadcrumbs.text-sm.mb-5
  %ul
    %li
      = link_to "Summary", root_path
    %li
      = "Disbursements for #{@year}"

%h1.text-3xl.mb-5.text-primary.font-bold
  = "Disbursements for #{@year}"

%table.table.table-zebra
  %thead
    %tr
      %th Date
      %th Amount
      %th Commission fee
      %th Merchant
      %th Orders
  %tbody
    - @disbursements.each do |disbursement|
      %tr
        %td= disbursement.as_of_date
        %td= disbursement.amount.format
        %td= disbursement.commission_fee.format
        %td= disbursement.merchant.reference
        %td= link_to "View orders", orders_path(disbursement_reference: disbursement.reference), class: "btn btn-sm btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "SeQura Challenge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.svg" type="image/svg+xml">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen flex flex-col">
    <main class="container mx-auto my-10 px-5 flex-grow">
      <%= yield %>
    </main>

    <footer class="footer sm:footer-horizontal footer-center bg-base-200 text-base-content p-4">
      <aside>
        <p>Created by <a href="https://github.com/glaucocustodio" target="_blank">Glauco Custodio</a></p>
      </aside>
    </footer>
  </body>
</html>

app/views/monthly_fees/index.haml
.breadcrumbs.text-sm.mb-5
  %ul
    %li
      = link_to "Summary", root_path
    %li
      = "Monthly fees for #{@year}"

%h1.text-3xl.mb-5.text-primary.font-bold
  = "Monthly fees for #{@year}"

%table.table.table-zebra
  %thead
    %tr
      %th Date
      %th Amount
      %th Merchant
  %tbody
    - @monthly_fees.each do |monthly_fee|
      %tr
        %td= monthly_fee.as_of_date
        %td= monthly_fee.fee.format
        %td= monthly_fee.merchant.reference

app/views/orders/index.haml
.breadcrumbs.text-sm.mb-5
  %ul
    %li
      = link_to "Summary", root_path
    %li
      = link_to "Disbursements for #{@disbursement.as_of_date.year}", disbursements_path(year: @disbursement.as_of_date.year)
    %li
      = "Orders for disbursement #{@disbursement.reference}"

%h1.text-3xl.mb-5.text-primary.font-bold
  = "Orders for disbursement #{@disbursement.reference}"

%table.table.table-zebra
  %thead
    %tr
      %th Amount
      %th Commission fee
      %th Merchant
      %th Placed at

  %tbody
    - @orders.each do |order|
      %tr
        %td= order.amount.format
        %td= order.commission_fee.format
        %td= order.merchant.reference
        %td= order.placed_at

app/views/summary/index.haml
%h1.text-3xl.mb-5.text-primary.font-bold
  Summary

%table.table
  %thead
    %tr
      %th Year
      %th Disbursements
      %th Disbursed to merchants
      %th Commission fees
      %th Amount of monthly fees
      %th Monthly fees
      %th

  %tbody
    - @summary.each do |summary|
      %tr
        %td= summary.year
        %td= summary.disbursements_count
        %td= summary.amount.format
        %td= summary.commission_fee.format
        %td= summary.monthly_fees_count
        %td= Money.from_cents(summary.monthly_fee_in_cents).format
        %td
          = link_to "View disbursements", disbursements_path(year: summary.year), class: "btn btn-sm"
          = link_to "View monthly fees", monthly_fees_path(year: summary.year), class: "btn btn-sm btn-primary"